source('./r/construct_multipartite_graph.R')
source('./r/to_laplacian.R')
# source('./r/cluster_multipartite_graph.R')
source('./r/read_and_preprocess_data.R')
source('./r/remove_flags_from_drug_categories.R')
# source('./r/count_clusters_per_category.R')
